[items]
stone = "Stone"
dirt = "Dirt"
sand = "Sand"
glass = "Glass"
grass = "Grass"
wood-pole = "Wood Pole"
tree-trunk = "Tree Trunk"
leaves = "Leaves"
tall-grass = "Tall Grass"
dead-shrub = "Dead Shrub"
boulder = "Boulder"
water = "Water"
oil = "Oil"
bonfire = "Bonfire"
chest = "Chest"
item-fan = "Item Fan"
rope-ladder = "Rope Ladder"
coal-outcrop = "Coal Outcrop"
iron-outcrop = "Iron Outcrop"
copper-outcrop = "Copper Outcrop"
sulphur-outcrop = "Sulphur Outcrop"
glass-pipe = "Glass Pipe"
torch = "Torch"
axe = "Axe"
dynamite = "Dynamite"
rock = "Rock"
coal = "Coal"
pig-iron = "Pig Iron"
iron-ore-chunk = "Iron Ore Chunk"
copper-ore-chunk = "Copper Ore Chunk"
sulphur = "Sulphur"
fiber = "Fiber"
stick = "Stick"
rope = "Rope"
