[items]
aqueduct = "Aqueduct"
stone = "Stone"
dirt = "Dirt"
sand = "Sand"
glass = "Glass"
grass = "Grass"
tree = "Tree"
wood = "Wood"
wood-pole = "Wood Pole"
leaves = "Leaves"
tall-grass = "Tall Grass"
dead-shrub = "Dead Shrub"
boulder = "Boulder"
water = "Water"
oil = "Oil"
bonfire = "Bonfire"
chest = "Chest"
clay = "Clay"
clay-tile = "Clay Tile"
item-fan = "Item Fan"
rope-ladder = "Rope Ladder"
coal-outcrop = "Coal Outcrop"
iron-outcrop = "Iron Outcrop"
copper-outcrop = "Copper Outcrop"
sulphur-outcrop = "Sulphur Outcrop"
glass-pipe = "Glass Pipe"
torch = "Torch"
axe = "Axe"
dynamite = "Dynamite"
rock = "Rock"
coal = "Coal"
pig-iron = "Pig Iron"
iron-ore-chunk = "Iron Ore Chunk"
copper = "Copper"
copper-ore-chunk = "Copper Ore Chunk"
sulphur = "Sulphur"
fiber = "Fiber"
stick = "Stick"
rope = "Rope"
unfired-crucible = "Crucible (unfired)"
crucible = "Crucible"
burned-food = "Burned Food"
potato = "Potato"
cooked-potato = "Cooked Potato"
potato-bush = "Potato Bush"
