[variants]
cross = ['./cross.png']
lone = ['./lone.png']

lu = ['./elbow.png', 'vflip']
ld = ['./elbow.png']
ru = ['./elbow.png', 'vflip', 'hflip']
rd = ['./elbow.png', 'hflip']

h = ['./line.png']
v = ['./line.png', 'transpose']

l = ['./open.png', 'rotate180']
r = ['./open.png']
u = ['./open.png', 'rotate90']
d = ['./open.png', 'rotate270']

lru = ['./tee.png', 'vflip']
lrd = ['./tee.png', ]
udl = ['./tee.png', 'rotate270']
udr = ['./tee.png', 'rotate270', 'hflip']
