name: Check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
        compiler: [g++, clang++]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: build-essential meson cmake python3 capnproto libcapnp-dev libglfw3-dev clang
        version: ${{matrix.os}}-1
    - name: setup
      run: CXX=${{matrix.compiler}} meson setup build -Dwerror=true
    - name: compile
      run: ninja -C build
    - name: check
      run: make check
